//Draft of file for getting the user's location using native Windows API or falling back to IP-Based geolocation.
//The Lat and Long are returned as an array of doubles.. We can convert to string if the other APIs need it!
//Also helps my wrist movement :D

//Import Statements
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.URL;

//GetUserLocation class
public class GetUserLocation 
{
    //Driver
    public static void main(String[] args) 
    {
        try 
        {
            double[] coords = getCoordinates();
            System.out.printf("Latitude:  %.6f%n", coords[0]);
            System.out.printf("Longitude: %.6f%n", coords[1]);
            System.out.printf("Source:    %s%n", coords[2] > 0 ? "Native (Â±" + (int) coords[2] + "m)" : "IP Fallback (~5-50km)");
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
    }

    //Returns [lat, lon, accuracyMeters] 
    //Accuracy is 0 for IP fallback or the actual accuracy in meters for native location
    public static double[] getCoordinates() 
    {
        try 
        {
            return getNativeCoordinates();
        } 
        catch (Exception e) 
        {
            System.err.println("Native location unavailable, falling back to IP geolocation.");
        }
        try 
        {
            return getIpCoordinates();
        } 
        catch (Exception e) 
        {
            throw new RuntimeException("All location methods failed.", e);
        }
    }

    //getNativeCoordinates method for getting user's location using Windows API via PowerShell
    private static double[] getNativeCoordinates() throws Exception 
    {
        // PowerShell script to get location using Windows.Devices.Geolocation API (shamelessly generated by Claude lol)
        String ps = String.join("\n",
            "Add-Type -AssemblyName System.Runtime.WindowsRuntime",
            "$asTaskGeneric = ([System.WindowsRuntimeSystemExtensions].GetMethods() |",
            "    Where-Object { $_.Name -eq 'AsTask' -and $_.GetParameters().Count -eq 1 -and",
            "    $_.GetParameters()[0].ParameterType.Name -eq 'IAsyncOperation`1' })[0]",
            "Function Await($WinRtTask, $ResultType) {",
            "    $asTask = $asTaskGeneric.MakeGenericMethod($ResultType)",
            "    $netTask = $asTask.Invoke($null, @($WinRtTask))",
            "    $netTask.Wait(-1) | Out-Null",
            "    $netTask.Result",
            "}",
            "[Windows.Devices.Geolocation.Geolocator, Windows.Devices.Geolocation, ContentType=WindowsRuntime] | Out-Null",
            "$g = New-Object Windows.Devices.Geolocation.Geolocator",
            "$g.DesiredAccuracyInMeters = 10",
            "$pos = Await $g.GetGeopositionAsync() ([Windows.Devices.Geolocation.Geoposition])",
            "Write-Output \"LAT=$($pos.Coordinate.Point.Position.Latitude)\"",
            "Write-Output \"LON=$($pos.Coordinate.Point.Position.Longitude)\"",
            "Write-Output \"ACC=$($pos.Coordinate.Accuracy)\""
        );

        //ProcessBuilder to execute the PowerShell script
        ProcessBuilder pb = new ProcessBuilder(
            "powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps
        );
        pb.redirectErrorStream(true);
        Process proc = pb.start();

        //StringBuilder to capture the output from the PowerShell script
        StringBuilder out = new StringBuilder();
        try (BufferedReader r = new BufferedReader(new InputStreamReader(proc.getInputStream()))) 
        {
            String line;
            while ((line = r.readLine()) != null) out.append(line).append("\n");
        }
        if (proc.waitFor() != 0) throw new RuntimeException("PowerShell failed:\n" + out);
        
        //Parse the output for LAT, LON, and ACC values and return them as a double array
        String result = out.toString();
        return new double[]
        {
            parseValue(result, "LAT="),
            parseValue(result, "LON="),
            parseValue(result, "ACC=")
        };
    }

    //getIpCoordinates method for getting user's location using IP-based geolocation
    //This is the fallback if native geolocation fails
    private static double[] getIpCoordinates() throws Exception 
    {
        //Query ip-api.com
        URL url = URI.create("http://ip-api.com/json").toURL();
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("GET");
        conn.setConnectTimeout(5000);
        conn.setReadTimeout(5000);

        //Check if successful
        if (conn.getResponseCode() != 200)
            throw new RuntimeException("HTTP " + conn.getResponseCode());

        //Read our JSON response
        StringBuilder json = new StringBuilder();
        try (BufferedReader r = new BufferedReader(new InputStreamReader(conn.getInputStream()))) {
            String line;
            while ((line = r.readLine()) != null) json.append(line);
        }

        //Parse the JSON for lat and long and return the relative accuracy
        String resp = json.toString();
        return new double[]{
            parseJsonDouble(resp, "lat"),
            parseJsonDouble(resp, "lon"),
            0 // no accuracy metric from IP geolocation
        };
    }

    //Helper method for parsing the powershell output
    private static double parseValue(String output, String prefix) 
    {
        for (String line : output.split("\n")) 
        {
            if (line.trim().startsWith(prefix))
                return Double.parseDouble(line.trim().substring(prefix.length()).trim());
        }
        throw new RuntimeException("Missing " + prefix + " in output");
    }

    //Helper method for parsing JSON double values
    private static double parseJsonDouble(String json, String key) 
    {
        String search = "\"" + key + "\":";
        int start = json.indexOf(search);
        if (start == -1) throw new RuntimeException("Key \"" + key + "\" not found");
        start += search.length();
        int end = start;
        while (end < json.length() && json.charAt(end) != ',' && json.charAt(end) != '}') end++;
        return Double.parseDouble(json.substring(start, end).trim());
    }
}